version: '3.9'

services:

  library_service:
    restart: on-failure
    container_name: library_service
    build: library_service/
    ports:
      - "8000:80"

  search_service:
    restart: on-failure
    container_name: search_service
    build: search_service/
    ports:
      - "8001:80"
